# Generated by Django 3.2.25 on 2024-05-31 20:16

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Home Page', 'verbose_name_plural': 'Home Pages'},
        ),
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('banner', wagtail.blocks.StructBlock([('banner_slides', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('background_image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('slide_title', wagtail.blocks.CharBlock(max_length=255, required=True)), ('slide_description', wagtail.blocks.TextBlock(required=True)), ('button_text', wagtail.blocks.CharBlock(max_length=50, required=False)), ('button_link', wagtail.blocks.URLBlock(required=False))])))])), ('about_section', wagtail.blocks.StructBlock([('features', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('background_image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('icon', wagtail.blocks.CharBlock(help_text="Enter the icon class name (e.g., 'flaticon-example')", required=True)), ('feature_title', wagtail.blocks.CharBlock(max_length=255, required=True)), ('feature_description', wagtail.blocks.TextBlock(required=True))]))), ('title', wagtail.blocks.CharBlock(max_length=255, required=True)), ('description', wagtail.blocks.RichTextBlock()), ('main_image_1', wagtail.images.blocks.ImageChooserBlock(required=True)), ('main_image_2', wagtail.images.blocks.ImageChooserBlock(required=True))])), ('team_carousel', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=255, required=True)), ('subtitle', wagtail.blocks.CharBlock(max_length=255, required=True)), ('description', wagtail.blocks.TextBlock(required=True)), ('members', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('name', wagtail.blocks.CharBlock(max_length=255, required=True)), ('designation', wagtail.blocks.CharBlock(max_length=255, required=True)), ('facebook_link', wagtail.blocks.URLBlock(required=False)), ('twitter_link', wagtail.blocks.URLBlock(required=False)), ('linkedin_link', wagtail.blocks.URLBlock(required=False))])))])), ('call_to_action', wagtail.blocks.StructBlock([('background_image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('title', wagtail.blocks.CharBlock(max_length=255, required=True)), ('text', wagtail.blocks.RichTextBlock()), ('button_1_text', wagtail.blocks.CharBlock(max_length=50, required=True)), ('button_1_link', wagtail.blocks.URLBlock(required=True)), ('button_2_text', wagtail.blocks.CharBlock(max_length=50, required=True)), ('button_2_link', wagtail.blocks.URLBlock(required=True))])), ('alternate_call_to_action', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=255, required=True)), ('button_text', wagtail.blocks.CharBlock(max_length=50, required=True)), ('button_link', wagtail.blocks.URLBlock(required=True))])), ('upcoming_events', wagtail.blocks.StructBlock([('subtitle', wagtail.blocks.CharBlock(max_length=255, required=True)), ('title', wagtail.blocks.CharBlock(max_length=255, required=True)), ('description', wagtail.blocks.TextBlock(required=True)), ('events', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('title', wagtail.blocks.CharBlock(max_length=255, required=True)), ('description', wagtail.blocks.TextBlock(required=True)), ('time', wagtail.blocks.CharBlock(max_length=50, required=True)), ('location', wagtail.blocks.CharBlock(max_length=255, required=True)), ('link_text', wagtail.blocks.CharBlock(max_length=50, required=True)), ('link_url', wagtail.blocks.URLBlock(required=True))])))]))], blank=True, null=True, use_json_field=None),
        ),
    ]
