# Generated by Django 3.2.25 on 2024-06-04 17:52

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('home', '0003_alter_homepage_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('banner_image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('banner_title', wagtail.blocks.CharBlock(max_length=255, required=True)), ('banner_subtitle', wagtail.blocks.CharBlock(max_length=255, required=True)), ('about_main_title', wagtail.blocks.CharBlock(max_length=255, required=True)), ('about_main_text', wagtail.blocks.RichTextBlock()), ('about_image_1', wagtail.images.blocks.ImageChooserBlock(required=True)), ('about_image_2', wagtail.images.blocks.ImageChooserBlock(required=True)), ('features', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=255, required=True)), ('text', wagtail.blocks.TextBlock(required=True))]))), ('causes', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=255, required=True)), ('text', wagtail.blocks.TextBlock(required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('raised', wagtail.blocks.CharBlock(max_length=255, required=True)), ('goal', wagtail.blocks.CharBlock(max_length=255, required=True)), ('progress', wagtail.blocks.CharBlock(max_length=3, required=True))]))), ('services', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('icon', wagtail.blocks.CharBlock(max_length=50, required=True)), ('title', wagtail.blocks.CharBlock(max_length=255, required=True)), ('text', wagtail.blocks.TextBlock(required=True))]))), ('team', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock(max_length=255, required=True)), ('designation', wagtail.blocks.CharBlock(max_length=255, required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('social_links', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('platform', wagtail.blocks.CharBlock(max_length=50, required=True)), ('url', wagtail.blocks.URLBlock(required=True))])))])))], blank=True, null=True, use_json_field=None)),
            ],
            options={
                'verbose_name': 'About Page',
                'verbose_name_plural': 'About Pages',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Home Page'},
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='body',
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_section',
            field=wagtail.fields.StreamField([('feature', wagtail.blocks.StructBlock([('icon', wagtail.blocks.CharBlock(required=True)), ('title', wagtail.blocks.CharBlock(required=True)), ('description', wagtail.blocks.TextBlock(required=True)), ('link_text', wagtail.blocks.CharBlock(required=True)), ('link_url', wagtail.blocks.URLBlock(required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(required=True))])), ('about_content', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=True)), ('subtitle', wagtail.blocks.CharBlock(required=True)), ('description', wagtail.blocks.TextBlock(required=True)), ('button_text', wagtail.blocks.CharBlock(required=True)), ('button_link', wagtail.blocks.URLBlock(required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(required=True))]))], blank=True, null=True, use_json_field=None),
        ),
        migrations.AddField(
            model_name='homepage',
            name='banner_section',
            field=wagtail.fields.StreamField([('banner', wagtail.blocks.StructBlock([('background_image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('title', wagtail.blocks.CharBlock(required=True)), ('description', wagtail.blocks.TextBlock(required=True)), ('button_text', wagtail.blocks.CharBlock(required=True)), ('button_link', wagtail.blocks.URLBlock(required=True))]))], blank=True, null=True, use_json_field=None),
        ),
        migrations.AddField(
            model_name='homepage',
            name='call_to_action',
            field=wagtail.fields.StreamField([('content', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=True)), ('description', wagtail.blocks.TextBlock(required=True)), ('button_text', wagtail.blocks.CharBlock(required=True)), ('button_link', wagtail.blocks.URLBlock(required=True)), ('background_image', wagtail.images.blocks.ImageChooserBlock(required=True))]))], blank=True, null=True, use_json_field=None),
        ),
        migrations.AddField(
            model_name='homepage',
            name='how_it_works_section',
            field=wagtail.fields.StreamField([('process', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=True)), ('description', wagtail.blocks.TextBlock(required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('button_text', wagtail.blocks.CharBlock(required=True)), ('button_link', wagtail.blocks.URLBlock(required=True))]))], blank=True, null=True, use_json_field=None),
        ),
        migrations.AddField(
            model_name='homepage',
            name='team_section',
            field=wagtail.fields.StreamField([('content', wagtail.blocks.StructBlock([('subtitle', wagtail.blocks.CharBlock(required=True)), ('title', wagtail.blocks.CharBlock(required=True)), ('description', wagtail.blocks.TextBlock(required=True))])), ('team_members', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock(required=True)), ('designation', wagtail.blocks.CharBlock(required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('facebook', wagtail.blocks.URLBlock(required=False)), ('twitter', wagtail.blocks.URLBlock(required=False)), ('linkedin', wagtail.blocks.URLBlock(required=False))])))], blank=True, null=True, use_json_field=None),
        ),
        migrations.AddField(
            model_name='homepage',
            name='upcoming_events',
            field=wagtail.fields.StreamField([('event', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=True)), ('description', wagtail.blocks.TextBlock(required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('time', wagtail.blocks.CharBlock(required=True)), ('location', wagtail.blocks.CharBlock(required=True)), ('button_text', wagtail.blocks.CharBlock(required=True)), ('button_link', wagtail.blocks.URLBlock(required=True))]))], blank=True, null=True, use_json_field=None),
        ),
        migrations.AddField(
            model_name='homepage',
            name='what_we_do_section',
            field=wagtail.fields.StreamField([('content', wagtail.blocks.StructBlock([('background_image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('subtitle', wagtail.blocks.CharBlock(required=True)), ('title', wagtail.blocks.CharBlock(required=True)), ('description', wagtail.blocks.TextBlock(required=True))])), ('services', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('icon', wagtail.blocks.CharBlock(required=True)), ('title', wagtail.blocks.CharBlock(required=True)), ('description', wagtail.blocks.TextBlock(required=True))])))], blank=True, null=True, use_json_field=None),
        ),
    ]
