# Generated by Django 3.2.25 on 2024-06-04 18:36

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20240604_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='services',
            field=wagtail.fields.StreamField([('services', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('icon', wagtail.blocks.CharBlock(required=True)), ('title', wagtail.blocks.CharBlock(required=True)), ('description', wagtail.blocks.TextBlock(required=True))])))], blank=True, null=True, use_json_field=None),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='body',
            field=wagtail.fields.StreamField([('banner_image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('banner_title', wagtail.blocks.CharBlock(max_length=255, required=True)), ('banner_subtitle', wagtail.blocks.CharBlock(max_length=255, required=True)), ('about_main_title', wagtail.blocks.CharBlock(max_length=255, required=True)), ('about_main_text', wagtail.blocks.RichTextBlock()), ('about_image_1', wagtail.images.blocks.ImageChooserBlock(required=True)), ('about_image_2', wagtail.images.blocks.ImageChooserBlock(required=True)), ('features', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=255, required=True)), ('text', wagtail.blocks.TextBlock(required=True))]))), ('services', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('icon', wagtail.blocks.CharBlock(max_length=50, required=True)), ('title', wagtail.blocks.CharBlock(max_length=255, required=True)), ('text', wagtail.blocks.TextBlock(required=True))]))), ('team', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock(max_length=255, required=True)), ('designation', wagtail.blocks.CharBlock(max_length=255, required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('social_links', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('platform', wagtail.blocks.CharBlock(max_length=50, required=True)), ('url', wagtail.blocks.URLBlock(required=True))])))])))], blank=True, null=True, use_json_field=None),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='what_we_do_section',
            field=wagtail.fields.StreamField([('content', wagtail.blocks.StructBlock([('background_image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('subtitle', wagtail.blocks.CharBlock(required=True)), ('title', wagtail.blocks.CharBlock(required=True)), ('description', wagtail.blocks.TextBlock(required=True))]))], blank=True, null=True, use_json_field=None),
        ),
    ]
