# Generated by Django 3.2.25 on 2024-06-04 19:17

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20240604_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='about_section',
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_section_content',
            field=wagtail.fields.StreamField([('about_content', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=True)), ('subtitle', wagtail.blocks.CharBlock(required=True)), ('description', wagtail.blocks.TextBlock(required=True)), ('button_text', wagtail.blocks.CharBlock(required=True)), ('button_link', wagtail.blocks.URLBlock(required=True)), ('image_1', wagtail.images.blocks.ImageChooserBlock(required=True)), ('image_2', wagtail.images.blocks.ImageChooserBlock(required=True))]))], blank=True, null=True, use_json_field=None),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_section_feature',
            field=wagtail.fields.StreamField([('feature', wagtail.blocks.StructBlock([('icon', wagtail.blocks.CharBlock(required=True)), ('title', wagtail.blocks.CharBlock(required=True)), ('description', wagtail.blocks.TextBlock(required=True)), ('link_text', wagtail.blocks.CharBlock(required=True)), ('link_url', wagtail.blocks.URLBlock(required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(required=True))]))], blank=True, null=True, use_json_field=None),
        ),
    ]
