# Generated by Django 3.2.25 on 2024-06-04 19:35

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_homepage_about_section_feature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='how_it_works_section',
        ),
        migrations.AddField(
            model_name='homepage',
            name='how_it_works_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='how_it_works_processes',
            field=wagtail.fields.StreamField([('process', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=True)), ('description', wagtail.blocks.TextBlock(required=True)), ('link_text', wagtail.blocks.CharBlock(required=True)), ('link_url', wagtail.blocks.URLBlock(required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(required=True))]))], blank=True, null=True, use_json_field=None),
        ),
        migrations.AddField(
            model_name='homepage',
            name='how_it_works_subtitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='how_it_works_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
