# Generated by Django 3.2.25 on 2024-06-04 20:41

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_homepage_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='upcoming_events',
            field=wagtail.fields.StreamField([('content', wagtail.blocks.StructBlock([('subtitle', wagtail.blocks.CharBlock(required=True)), ('title', wagtail.blocks.CharBlock(required=True)), ('description', wagtail.blocks.TextBlock(required=True))])), ('event', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('time', wagtail.blocks.CharBlock(required=True)), ('location', wagtail.blocks.CharBlock(required=True)), ('button_text', wagtail.blocks.CharBlock(required=True)), ('button_link', wagtail.blocks.URLBlock(required=True))]))], blank=True, null=True, use_json_field=None),
        ),
    ]
