# Generated by Django 3.2.25 on 2024-06-04 21:12

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('home', '0013_alter_homepage_upcoming_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='body',
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='about_section',
            field=wagtail.fields.StreamField([('content', wagtail.blocks.StructBlock([('subtitle', wagtail.blocks.CharBlock(required=True)), ('title', wagtail.blocks.CharBlock(required=True)), ('description', wagtail.blocks.TextBlock(required=True)), ('button_text', wagtail.blocks.CharBlock(required=True)), ('button_link', wagtail.blocks.URLBlock(required=True)), ('image_1', wagtail.images.blocks.ImageChooserBlock(required=True)), ('image_2', wagtail.images.blocks.ImageChooserBlock(required=True))]))], blank=True, null=True, use_json_field=None),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='about_section_features',
            field=wagtail.fields.StreamField([('feature', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=True)), ('description', wagtail.blocks.TextBlock(required=True))]))], blank=True, null=True, use_json_field=None),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='banner_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='team_section',
            field=wagtail.fields.StreamField([('content', wagtail.blocks.StructBlock([('subtitle', wagtail.blocks.CharBlock(required=True)), ('title', wagtail.blocks.CharBlock(required=True)), ('description', wagtail.blocks.TextBlock(required=True))])), ('team_members', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock(required=True)), ('designation', wagtail.blocks.CharBlock(required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('facebook', wagtail.blocks.URLBlock(required=False)), ('twitter', wagtail.blocks.URLBlock(required=False)), ('linkedin', wagtail.blocks.URLBlock(required=False))])))], blank=True, null=True, use_json_field=None),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='what_we_do_section',
            field=wagtail.fields.StreamField([('content', wagtail.blocks.StructBlock([('background_image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('subtitle', wagtail.blocks.CharBlock(required=True)), ('title', wagtail.blocks.CharBlock(required=True)), ('description', wagtail.blocks.TextBlock(required=True))])), ('services', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('icon', wagtail.blocks.CharBlock(required=True)), ('title', wagtail.blocks.CharBlock(required=True)), ('description', wagtail.blocks.TextBlock(required=True))])))], blank=True, null=True, use_json_field=None),
        ),
    ]
