# Generated by Django 3.2.25 on 2024-06-05 19:12

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('wagtailcore', '0083_workflowcontenttype'),
        ('home', '0014_auto_20240604_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='about_section',
            field=wagtail.fields.StreamField([('content', wagtail.blocks.StructBlock([('subtitle', wagtail.blocks.CharBlock(required=True)), ('title', wagtail.blocks.CharBlock(required=True)), ('description', wagtail.blocks.TextBlock(required=True)), ('button_text', wagtail.blocks.CharBlock(blank=True, null=True, required=False)), ('button_link', wagtail.blocks.URLBlock(blank=True, null=True, required=False)), ('image_1', wagtail.images.blocks.ImageChooserBlock(required=True)), ('image_2', wagtail.images.blocks.ImageChooserBlock(required=True))]))], blank=True, null=True, use_json_field=None),
        ),
        migrations.CreateModel(
            name='FAQPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro_title', models.CharField(max_length=255)),
                ('intro_description', models.TextField()),
                ('faq_sections', wagtail.fields.StreamField([('faq_section', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=True)), ('questions', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('question', wagtail.blocks.CharBlock(required=True)), ('answer', wagtail.blocks.TextBlock(required=True))])))]))], blank=True, null=True, use_json_field=None)),
                ('banner_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'FAQ Page',
                'verbose_name_plural': 'FAQ Pages',
            },
            bases=('wagtailcore.page',),
        ),
    ]
