# Generated by Django 3.2.25 on 2024-06-05 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20240605_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqpage',
            name='introduction',
            field=models.TextField(blank=True),
        ),
    ]
