# Generated by Django 3.2.25 on 2024-06-05 19:25

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_faqpage_introduction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faqpage',
            options={},
        ),
        migrations.RemoveField(
            model_name='faqpage',
            name='banner_image',
        ),
        migrations.RemoveField(
            model_name='faqpage',
            name='intro_description',
        ),
        migrations.RemoveField(
            model_name='faqpage',
            name='intro_title',
        ),
        migrations.AlterField(
            model_name='faqpage',
            name='faq_sections',
            field=wagtail.fields.StreamField([('faq_section', wagtail.blocks.StructBlock([('section_title', wagtail.blocks.CharBlock(required=True)), ('faqs', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('question', wagtail.blocks.CharBlock(required=True)), ('answer', wagtail.blocks.TextBlock(required=True))])))]))], blank=True, null=True, use_json_field=None),
        ),
    ]
